---
title: "Homework 5"
author: "Ani Bilazarian"
date: "11/8/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


# Problem 1 

_Read in IRIS data_

```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

_Function replacing NAs_

```{r}

missing_data = function(x)  {
  
  if(is.numeric(x)){
    x = replace_na(x, mean(x, na.rm = TRUE))
  } 
  else if (is.character(x)){
    x = replace_na(x, "virginica")
  
    }}
  
iris_with_missing =  map(iris_with_missing, missing_data) %>% 
  as_tibble()
```


# PROBLEM 2

_ Writing Function to Import Multiple Files at Once_ 

```{r, warning = FALSE, message= FALSE}
library(readxl)

files = list.files("./data", pattern = NULL, all.files = FALSE, full.names = FALSE) 

problem_2 = data_frame(filename = files) %>% 
mutate(file_contents = map(filename, ~ read_csv(file.path("./data", .)))) %>% 
separate("filename", into = c("control", "subject")) %>% 
  unnest(file_contents) %>% 
  mutate(control = recode(control, 'con' = "control", 'exp' =  "experimental"))
```

_Spaghetti Plot Separated by Face_Grid to show Control versus Experimental_

```{r}
problem_2 %>% 
pivot_longer(week_1:week_8, names_to = "week", names_prefix = "week_") %>% 
  ggplot(aes(x = week, y = value, group = subject, color = subject)) + geom_path() + labs(title = "Distribution of Observations Across Weeks") + facet_grid(~control) + viridis::scale_color_viridis(discrete = TRUE) + theme(legend.position = "bottom")
```

_Spaghetti Plot on one graph showing Control and Experimental_

```{r}
problem_2 %>% 
  pivot_longer(week_1:week_8, names_to = "week", names_prefix = "week_") %>% 
  ggplot(aes(x = week, y = value, group = subject, color = control)) + geom_path() + labs(title = "Distribution of Observations Across Weeks") + viridis::scale_color_viridis(discrete = TRUE) + theme(legend.position = "bottom")

```







